python ../txt_to_png.py b0.txt b0.png
python ../txt_to_png.py b1.txt b1.png
python ../txt_to_png.py b2.txt b2.png
python ../txt_to_png.py b3.txt b3.png
python ../txt_to_png.py w0-0.txt w0-0.png
python ../txt_to_png.py w0-1.txt w0-1.png
python ../txt_to_png.py w1-0.txt w1-0.png
python ../txt_to_png.py w1-1.txt w1-1.png
python ../txt_to_png.py w1-2.txt w1-2.png
python ../txt_to_png.py w1-3.txt w1-3.png
python ../txt_to_png.py w2.txt w2.png
python ../txt_to_png.py w3.txt w3.png
